name: Automated Tests
on:
  # Run on pushs
  push:
    # To main
    branches:
      - main
jobs:
  pest:
    name: Run Pest Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug

      - uses: ramsey/composer-install@v2
        with:
          composer-options: --quiet

      - name: Run Pest
        run: vendor/bin/pest --colors=always --coverage